# _config.yml

title: Sustainability & Environmental Analyst
description: Welcome to my Data Analyst Portfolio! Explore my work, projects, and skills in data analysis, visualization, and insights.
#author:
  #name: Adeyemi Temitope Adejare
 #email: adejare.yemi@outlook.com
  #Ã¤url: https://temmythourpe.github.io/portfolio/

# Configuration for Jekyll theme (Example: Minimal Mistakes)
theme: jekyll-theme-minimal
